GET http://localhost:3000/users
Authorization: Bearer ADMIN_TOKEN_HERE
Accept: application/json
###

# USERS TESTS
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@admin.com",
  "password": "password123",
  "role": "Admin"
}
###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "password123"
}

###

# TODO TESTS

GET http://localhost:3000/todo
Accept: application/json
###

GET http://localhost:3000/todo/habits
Authorization: Bearer YOUR_TOKEN_HERE
Accept: application/json
###

POST http://localhost:3000/todo/habits
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "title": "Drink Water"
}
###

GET http://localhost:3000/todo/workouts
Accept: application/json
###

POST http://localhost:3000/todo/workouts
Authorization: Bearer ADMIN_TOKEN_HERE
Content-Type: application/json

{
  "title": "Bench Press"
}
###

GET http://localhost:3000/todo/admin/metrics
Authorization: Bearer ADMIN_TOKEN_HERE
Accept: application/json
###

# HOME TESTS
GET http://localhost:3000/home/
Accept: application/json
###
