GET http://localhost:3000/users
Accept: application/json
###

# USERS TESTS
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "password123"
}
###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "password123"
}

###

# TODO TESTS

GET http://localhost:3000/todo
Accept: application/json
###

GET http://localhost:3000/todo/habits
Accept: application/json
###

POST http://localhost:3000/todo/habits
Content-Type: application/json

{
  "title": "Drink Water"
}
###

GET http://localhost:3000/todo/workouts
Accept: application/json
###

POST http://localhost:3000/todo/workouts
Content-Type: application/json

{
  "title": "Bench Press"
}
###

POST http://localhost:3000/todo/set_workouts
Content-Type: application/json

{
  "user_id": 1,
  "workout_id": 4,
  "reps": 10,
  "sets": 3,
  "weight": 150
}
###

POST http://localhost:3000/todo/set_habits
Content-Type: application/json

{
  "user_id": 1,
  "habit_id": 2
}
###

# HOME TESTS
GET http://localhost:3000/home/
Accept: application/json
###